{
 "title": "Gatling Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "User",
    "query": {}
   },
   {
    "name": "Simulation",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Total Request Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "gatling.$User.$Simulation.*.allRequests.all.count"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "gatling.$User.$Simulation.*.allRequests.ko.count"
    }
   ]
  },
  {
   "title": "Total OK Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "gatling.$User.$Simulation.*.allRequests.ok.count"
    }
   ]
  },
  {
   "title": "Average Request Times",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "gatling.$User.$Simulation.*.allRequests.all.min"
    },
    {
     "target": "gatling.$User.$Simulation.*.allRequests.all.mean"
    },
    {
     "target": "gatling.$User.$Simulation.*.allRequests.all.max"
    }
   ]
  },
  {
   "title": "Users",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 17 },
   "targets": [
    {
     "target": "gatling.$User.$Simulation.*.users.allUsers.*"
    }
   ]
  },
  {
   "title": "Requests Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "target": "gatling.$User.$Simulation.*.allRequests.*.count"
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "gatling.$User.$Simulation.*.allRequests.all.mean"
    },
    {
     "target": "gatling.$User.$Simulation.*.allRequests.all.max"
    },
    {
     "target": "gatling.$User.$Simulation.*.allRequests.all.min"
    }
   ]
  },
  {
   "title": "Response Times Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "target": "gatling.$User.$Simulation.*.allRequests.all.percentiles99"
    },
    {
     "target": "gatling.$User.$Simulation.*.allRequests.all.percentiles95"
    },
    {
     "target": "gatling.$User.$Simulation.*.allRequests.all.percentiles75"
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 50 },
   "targets": [
    {
     "target": "gatling.$User.$Simulation.*.allRequests.all.mean"
    },
    {
     "target": "gatling.$User.$Simulation.*.allRequests.all.max"
    },
    {
     "target": "gatling.$User.$Simulation.*.allRequests.all.min"
    }
   ]
  }
 ]
}