variable "aws_region" {}
variable "aws_profile" {}
variable "aws_account_id" {}
variable "ecr_repository" {}
variable "slave_memory" {}
variable "slave_cpu" {}
variable "slave_count" {}
variable "s3_bucket_name" {}
variable "common_tags" {}
variable "subnet_id" {}
variable "security_group_id" {}
