{
 "title": "Telegraf Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Received and Transmitted Data",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "sumSeries(telegraf.*.*.*.*.*.loadtesting-task.*.loadtesting-task.*.loadtesting-container.eth1.*.*.ecs_container_net.rx_bytes)"
    },
    {
     "target": "sumSeries(telegraf.*.*.*.*.*.loadtesting-task.*.loadtesting-task.*.loadtesting-container.eth1.*.*.ecs_container_net.tx_bytes)"
    }
   ]
  },
  {
   "title": "Network Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "percent", "label": "CPU Usage" }
   ],
   "targets": [
    {
     "target": "telegraf.*.*.*.*.*.loadtesting-task.*.loadtesting-task.*.loadtesting-container.total.*.*.ecs_container_net.rx_bytes"
    },
    {
     "target": "telegraf.*.*.*.*.*.loadtesting-task.*.loadtesting-task.*.loadtesting-container.total.*.*.ecs_container_net.tx_bytes"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "telegraf.*.*.*.loadtesting-container.*.*.*.cpu-total.loadtesting-task.*.loadtesting-container.*.*.ecs_container_cpu.usage_percent"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "target": "telegraf.*.*.*.loadtesting-container.*.*.*.loadtesting-task.*.loadtesting-container.*.*.ecs_container_mem.usage"
    }
   ]
  }
 ]
}