apiVersion: 1
datasources:
  - name: graphite
    type: graphite
    access: proxy
    url: http://graphite.loadtest
    isDefault: true
    jsonData:
      graphiteVersion: "1.1"
      timeInterval: "1m"
